### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by louwaque**

### CODE REVIEW

**Comment by brunonova** [comment]
Hi! Thank you for your contribution.

I checked `po/fr.po`, and I found that some of the exclamation marks are separated from the previous word by a space, like in line 41:

```
msgstr "ATTENTION !"
```

Is this intentional?

---

Another thing. The comments in the first 4 lines still have the placeholders from the `.pot`.
I'll correct that myself after I merge the request (unless you want to do that).

I'll also add your name and email to the `AUTHORS` file, as a translator.

**Comment by louwaque** [comment]
Hi ! Spaces between words are intentional and required :)
As for placeholders, I left them empty because I never know if it's for me or the developer. And i'm ok for the author's file.

**Comment by brunonova** [comment]
Merged!

I had no idea that in French some punctuation marks must be preceded by a space. I learned something new today! :smile:

As for the placeholders, I also didn't know what fields I should fill as the developer.
However, the info page for `gettext` explains that a bit. It seems I have to fill a few more fields. :smile:.

I'll wait a few days to see if someone else sends me a translation for another language, then I'll release a new version.

**Comment by louwaque** [comment]
Cool :smiley: i'm waiting

**Comment by brunonova** [comment]
[New version released!](https://github.com/brunonova/nautilus-admin/releases/tag/v0.1.4)

**Comment by louwaque** [comment]
Cool ! 
nautilus admin

**Comment by brunonova** [comment]
:smiley: 
Thanks again for the translation!

**Comment by brunonova** [comment]
I've added a new feature to the extension, which added and changed some strings.
You're welcome to update your translation.

**Pull request merged**
