### PR TITLE
Add russian translation

### PR DESCRIPTION
**Pull request by DeadMetaler**

### CODE REVIEW

**Comment by brunonova** [comment]
Merged. Thank you for the translation!

I'll wait a week to see if I receive more translations for other languages, then I'll release a new version.

**Comment by brunonova** [comment]
[New version released!](https://github.com/brunonova/nautilus-admin/releases/tag/v0.1.5)

**Comment by DeadMetaler** [comment]
Thanks. Already updated.

**Comment by brunonova** [comment]
I've added a new feature to the extension, which added and changed some strings.
You're welcome to update your translation.

**Pull request merged**
