### PR TITLE
Add italian translation

### PR DESCRIPTION
**Pull request by Ste74**

### CODE REVIEW

**Comment by brunonova** [comment]
Great! Thank you for your translation!

There's just one problem: you removed a Spanish translation from the polkit file, probably accidentally.
But no worries, I'll re-add it later!

I'll way a few days to see if anyone else sends another translation for another language, then I'll release a new version.

**Comment by Ste74** [comment]
Damn it  :( .. sorry for mystake .. ok .. now this is part of manjaro

**Comment by brunonova** [comment]
No problem! To err is human.
I fixed that just now.

Thanks again!

**Comment by brunonova** [comment]
New version released.

**Comment by brunonova** [comment]
I've added a new feature to the extension, which added and changed some strings.
You're welcome to update your translation.

**Comment by Ste74** [comment]
Yep .. let me see the change :smile:

**Comment by brunonova** [comment]
I've updated the po files (with `msgmerge`).
The 3 strings that were changed are the ones marked as `fuzzy`. You (or anyone else) just need to update those and remove the respective `fuzzy` lines.

Thanks in advance!

**Pull request merged**
